# Settings
baseurl: /docet
permalink: pretty

# About
title: D.O.C.E.T
tagline: "DeFei Orationes, C... Et T..."
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu'
created: 2015
license:
  name: Creative Commons 4.0 Attribution-ShareAlike
  shortname: CC-BY-SA 4.0
  url: http://creativecommons.org/licenses/by-sa/4.0/
  badge: http://i.creativecommons.org/l/by-sa/4.0/80x15.png
  
# Collections
collections:
  addons:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

kramdown:
  parse_block_html: true
